package org.cougaar.mts.corba.idlj;


/**
* org/cougaar/mts/corba/idlj/_MTStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from src/org/cougaar/mts/corba/MT.idl
* Wednesday, October 27, 2004 1:32:23 PM EDT
*/

public class _MTStub extends org.omg.CORBA.portable.ObjectImpl implements org.cougaar.mts.corba.idlj.MT
{

  public byte[] rerouteMessage (byte[] message) throws org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessage, org.cougaar.mts.corba.idlj.CorbaDontRetryException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rerouteMessage", true);
                org.cougaar.mts.corba.idlj.bytesHelper.write ($out, message);
                $in = _invoke ($out);
                byte $result[] = org.cougaar.mts.corba.idlj.bytesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:cougaar/CorbaMisdeliveredMessage:1.0"))
                    throw org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessageHelper.read ($in);
                else if (_id.equals ("IDL:cougaar/CorbaDontRetryException:1.0"))
                    throw org.cougaar.mts.corba.idlj.CorbaDontRetryExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rerouteMessage (message        );
            } finally {
                _releaseReply ($in);
            }
  } // rerouteMessage

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cougaar/MT:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _MTStub
