package org.cougaar.mts.corba.idlj;


/**
* org/cougaar/mts/corba/idlj/CorbaDontRetryExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from src/org/cougaar/mts/corba/MT.idl
* Wednesday, October 27, 2004 1:32:23 PM EDT
*/

abstract public class CorbaDontRetryExceptionHelper
{
  private static String  _id = "IDL:cougaar/CorbaDontRetryException:1.0";

  public static void insert (org.omg.CORBA.Any a, org.cougaar.mts.corba.idlj.CorbaDontRetryException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.cougaar.mts.corba.idlj.CorbaDontRetryException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.cougaar.mts.corba.idlj.bytesHelper.id (), "bytes", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "cause",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (org.cougaar.mts.corba.idlj.CorbaDontRetryExceptionHelper.id (), "CorbaDontRetryException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.cougaar.mts.corba.idlj.CorbaDontRetryException read (org.omg.CORBA.portable.InputStream istream)
  {
    org.cougaar.mts.corba.idlj.CorbaDontRetryException value = new org.cougaar.mts.corba.idlj.CorbaDontRetryException ();
    // read and discard the repository ID
    istream.read_string ();
    value.cause = org.cougaar.mts.corba.idlj.bytesHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.cougaar.mts.corba.idlj.CorbaDontRetryException value)
  {
    // write the repository ID
    ostream.write_string (id ());
    org.cougaar.mts.corba.idlj.bytesHelper.write (ostream, value.cause);
  }

}
