package org.cougaar.mts.corba.idlj;


/**
* org/cougaar/mts/corba/idlj/MTOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from src/org/cougaar/mts/corba/MT.idl
* Wednesday, October 27, 2004 1:32:23 PM EDT
*/

public interface MTOperations 
{
  byte[] rerouteMessage (byte[] message) throws org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessage, org.cougaar.mts.corba.idlj.CorbaDontRetryException;
} // interface MTOperations
