package org.cougaar.mts.corba.idlj;

/**
 * org/cougaar/mts/corba/idlj/CorbaDontRetryException.java . Generated by the
 * IDL-to-Java compiler (portable), version "3.1" from
 * src/org/cougaar/mts/corba/MT.idl Wednesday, October 27, 2004 1:32:23 PM EDT
 */

public final class CorbaDontRetryException
        extends org.omg.CORBA.UserException {
    /**
    * 
    */
   private static final long serialVersionUID = 1L;
   public byte cause[] = null;

    public CorbaDontRetryException() {
        super(CorbaDontRetryExceptionHelper.id());
    } // ctor

    public CorbaDontRetryException(byte[] _cause) {
        super(CorbaDontRetryExceptionHelper.id());
        cause = _cause;
    } // ctor

    public CorbaDontRetryException(String $reason, byte[] _cause) {
        super(CorbaDontRetryExceptionHelper.id() + "  " + $reason);
        cause = _cause;
    } // ctor

} // class CorbaDontRetryException
