package org.cougaar.mts.corba.idlj;

/**
 * org/cougaar/mts/corba/idlj/CorbaMisdeliveredMessageHolder.java . Generated by
 * the IDL-to-Java compiler (portable), version "3.1" from
 * src/org/cougaar/mts/corba/MT.idl Wednesday, October 27, 2004 1:32:23 PM EDT
 */

public final class CorbaMisdeliveredMessageHolder
        implements org.omg.CORBA.portable.Streamable {
    public org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessage value = null;

    public CorbaMisdeliveredMessageHolder() {
    }

    public CorbaMisdeliveredMessageHolder(org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessage initialValue) {
        value = initialValue;
    }

    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessageHelper.read(i);
    }

    public void _write(org.omg.CORBA.portable.OutputStream o) {
        org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessageHelper.write(o, value);
    }

    public org.omg.CORBA.TypeCode _type() {
        return org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessageHelper.type();
    }

}
