package org.cougaar.mts.corba.idlj;

/**
 * org/cougaar/mts/corba/idlj/MT.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from src/org/cougaar/mts/corba/MT.idl Wednesday,
 * October 27, 2004 1:32:23 PM EDT
 */

public interface MT
        extends MTOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface MT
