package org.cougaar.mts.corba.idlj;


/**
* org/cougaar/mts/corba/idlj/MTPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from src/org/cougaar/mts/corba/MT.idl
* Wednesday, October 27, 2004 1:32:23 PM EDT
*/

public abstract class MTPOA extends org.omg.PortableServer.Servant
 implements org.cougaar.mts.corba.idlj.MTOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("rerouteMessage", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // cougaar/MT/rerouteMessage
       {
         try {
           byte message[] = org.cougaar.mts.corba.idlj.bytesHelper.read (in);
           byte $result[] = null;
           $result = this.rerouteMessage (message);
           out = $rh.createReply();
           org.cougaar.mts.corba.idlj.bytesHelper.write (out, $result);
         } catch (org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessage $ex) {
           out = $rh.createExceptionReply ();
           org.cougaar.mts.corba.idlj.CorbaMisdeliveredMessageHelper.write (out, $ex);
         } catch (org.cougaar.mts.corba.idlj.CorbaDontRetryException $ex) {
           out = $rh.createExceptionReply ();
           org.cougaar.mts.corba.idlj.CorbaDontRetryExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:cougaar/MT:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MT _this() 
  {
    return MTHelper.narrow(
    super._this_object());
  }

  public MT _this(org.omg.CORBA.ORB orb) 
  {
    return MTHelper.narrow(
    super._this_object(orb));
  }


} // class MTPOA
